---
- name: "Install term packages"
  become: true
  community.general.pacman:
    name:
      - bat
      - curl
      - duf
      - eza
      - fd
      - gcc # required for neovim/Mason
      - htop
      - jq
      - lazygit
      - most
      - ncdu
      - neovim
      - rclone
      - ripgrep
      - rsync
      - smartmontools
      - sshfs
      - tldr
      - tmux
      - tmuxp
      - ttf-firacode-nerd
      - unzip
      - wget
      - zip
      - zsh
    state: present

- name: "Install GUI packages"
  become: true
  community.general.pacman:
    name:
      - alacritty
      - xclip
    state: present
  when: "'xorg-server' in ansible_facts.packages"
