---
- name: "[Debian] Install term packages"
  become: yes
  community.general.pacman:
    name:
      - bat
      - curl
      - duf
      # - eza # not in debian
      - fd-find
      - gcc # required for neovim/Mason
      - gpg
      - htop
      - jq
      # - lazygit # not in debian
      - most
      - ncdu
      - neovim
      - rclone
      - ripgrep
      - rsync
      - smartmontools
      - sshfs
      - tldr
      - tmux
      # - ttf-firacode-nerd # not in debian
      - unzip
      - wget
      - zip
      - zsh
    state: present

- name: "[Debian] Install EZA (ls replacement)"
  become: yes
  shell: |
    sudo mkdir -p /etc/apt/keyrings
    wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
    echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
    sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
    sudo apt update
    sudo apt install -y eza

- name: "[Debian] Install GUI packages"
  become: yes
  community.general.pacman:
    name:
      - alacritty
      - xclip
    state: present
