---
- name: "Install term packages"
  become: true
  ansible.builtin.apt:
    name:
      - bat
      - curl
      - duf
      - fd-find
      - fontconfig
      - gcc # required for neovim/Mason
      - gpg
      - htop
      - jq
      - most
      - ncdu
      - rclone
      - ripgrep
      - rsync
      - smartmontools
      - sshfs
      - tldr
      - tmux
      - tmuxinator
      - unzip
      - wget
      - zip
      - zsh
    state: present

- name: "Install GUI packages"
  become: true
  ansible.builtin.apt:
    name:
      - alacritty
      - xclip
    state: present
  when: "'xorg-server' in ansible_facts.packages"

- name: "Install GUI packages"
  become: true
  ansible.builtin.apt:
    name:
      - alacritty
      - xclip
    state: present
  when: "'xorg-server' in ansible_facts.packages"

- name: Check if Alacritty is already in terminfo
  ansible.builtin.command: infocmp alacritty
  register: infocmp_result
  ignore_errors: true
  changed_when: false

- name: Add Alacritty to TERM info
  block:
    - name: Git checkout of Ansible source
      ansible.builtin.git:
        repo: "https://github.com/alacritty/alacritty.git"
        dest: /tmp/alacritty
    - name: Adding Alacritty to terminfo
      become: true
      ansible.builtin.shell: tic -xe alacritty,alacritty-direct extra/alacritty.info
      args:
        chdir: /tmp/alacritty
    - name: Removing Alacritty source
      become: true
      ansible.builtin.shell: rm -rf /tmp/alacritty
  when: infocmp_result is failed

##### EZA ######

- name: "EZA key exists"
  ansible.builtin.stat:
    path: "/etc/apt/keyrings/gierens.gpg"
  register: ezakey

- name: "Install EZA (ls replacement)"
  become: true
  shell: |
    sudo mkdir -p /etc/apt/keyrings
    wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
    echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
    sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
    sudo apt update
    sudo apt install -y eza
  when: not ezakey.stat.exists

##### FIRA CODE ######

- name: "Check if FiraCode font exists"
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.local/share/fonts/FiraCodeNerdFont-Regular.ttf"
  register: fira

- name: "Create font directory"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/fonts"
    state: directory
  when: not fira.stat.exists

- name: "FiraCode download"
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.0/FiraCode.zip
    dest: "{{ ansible_env.HOME }}/.local/share/fonts"
    remote_src: yes
  when: not fira.stat.exists

- name: "Reload font cache"
  shell: fc-cache -fv
  when: not fira.stat.exists

##### NEOVIM ######

- name: "Check if Neovim is installed"
  ansible.builtin.stat:
    path: "/opt/nvim"
  register: nvim

- name: "Install Neovim"
  become: true
  shell: |
    curl -o /tmp/neovim.tar.gz -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
    tar -C /opt -xzf /tmp/neovim.tar.gz
    rm -f /tmp/neovim.tar.gz
    mv /opt/nvim-linux64 /opt/nvim
  when: not nvim.stat.exists

  ##### LAZYGIT #####
  
- name: "Check if Lazygit is installed"
  ansible.builtin.stat:
    path: "/usr/bin/lazygit"
  register: lazygit

- name: "Install Lazygit"
  become: true
  shell: |
    curl -o /tmp/lazygit.tar.gz -LO https://github.com/jesseduffield/lazygit/releases/download/v0.41.0/lazygit_0.41.0_Linux_x86_64.tar.gz
    tar -C /usr/bin -xzf /tmp/lazygit.tar.gz lazygit
    rm -f /tmp/lazygit.tar.gz
  when: not lazygit.stat.exists
